[workspace]
resolver = "2"
members = [
    "deimosd",
    "deimos-shared",
    "deimos-client"
]

[workspace.dependencies]
rustls = { version = "0.23" }

serde = { version = "1.0", features = ["derive"] }

log = "0.4"

[workspace.dependencies.tonic]
version = "0.12"
default-features = false
features = ["tls", "transport", "prost"]

[workspace.dependencies.tokio]
version = "1.40"
