[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.25.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "$HOME/.local/bin"
# Whether to install an updater program
install-updater = false

github-build-setup = "build-install-protoc.yml"

[dist.dependencies.apt]
libx11-dev = '*'
libxext-dev = '*'
libxft-dev = '*'
libxinerama-dev = '*'
libxcursor-dev = '*'
libxrender-dev = '*'
libxfixes-dev = '*'
libgl1-mesa-dev = '*'
"libpango1.0-dev" = '*'
libglu1-mesa-dev = '*'
