[package]
name = "deimosctl"
version = "1.1.7"
edition = "2021"
dist = false

[dependencies]
clap =  { version = "4.5", features = ["derive"] }
deimosproto = { path = "../deimosproto" }

tokio = { workspace = true }
