[package]
name = "deimos-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
serde = { workspace = true }
chacha20poly1305 = { workspace = true }
tokio = { workspace = true }

thiserror = "1.0"
