[package]
name = "deimosd"
authors = ["Ben"]
version = "0.1.0"
edition = "2021"
license = "none"

[dependencies]
deimos-shared = { path = "../deimos-shared" }
tokio = { workspace = true, features = ["rt-multi-thread", "fs"] }
thiserror = "1.0"
futures = "0.3"

igd-next = { version = "0.15", features = ["aio_tokio"] }

bollard = "0.17"

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
toml = "0.8"


[package.metadata.deb]
maintainer-scripts = "debian"
systemd-units = { enable = true }
