[package]
name = "deimos-client"
version = "0.1.0"
edition = "2021"

[dependencies]
deimos-shared = { path = "../deimos-shared", features = ["channel"] }
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "macros"] }

tonic = { workspace = true, features = ["channel"] }
http = "1.1"
http-serde = "2.1"

serde = { workspace = true }
serde_json = "1.0"
dirs = "5.0"
thiserror = "1.0"

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }

[dependencies.iced]
version = "0.13"
features = ["tokio", "image", "svg"]

[dependencies.iced_aw]
version = "0.11"
features = ["spinner"]
