[package]
name = "deimos-client"
version = "0.1.0"
edition = "2021"

[dependencies]
deimos-shared = { path = "../deimos-shared" }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }

[dependencies.iced]
version = "0.12"
features = ["tokio", "image"]
