[package]
name = "deimos-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = { workspace = true }
tonic = { workspace = true, features = ["channel"] }
deimos-shared = { path = "../deimos-shared", features = ["channel"] }

[dependencies.iced]
version = "0.12"
features = ["tokio", "image"]
